### ISSUE TITLE
Advice needed on adding new Landsat USGS-derived "surface reflectance" data

### ISSUE THREAD

**Issue by bhbraswell** [Applied-GeoSolutions/gips#24] opened 2016-01-07 16:27 UTC
Landsat 8 provides it's own surface reflectance product. It has per-band values and a cloud mask. I can update the driver but am stuck on deciding what is the best approach, and on how Landsat bands are accessed in the first place. I think the way to go is to introduce _assets to landsatAsset. For example instead of just one key that is '', we could have two, one called "TOA", and one called "SR". The implication is that all the existing products would need to then be associated with an asset (TOA). That makes sense to me. Other input is welcome. I would then still need to understand how to create indices and whatever using the SR data that have a different file structure.

```
(venv)rbraswell@rio:/titan/data/landsat/stage/rbraswell$ tar -tvf LC81190622014027-SC20151105030019.tar.gz 
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band6.tif
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band5.tif
-rw-r--r-- espa/ie        9757 2015-11-05 04:00 LC81190622014027LGN00.xml
-rw-r--r-- espa/ie    59052412 2015-11-05 04:00 LC81190622014027LGN00_sr_cloud.tif
-rw-r--r-- espa/ie    59052374 2015-11-05 04:00 LC81190622014027LGN00_cfmask.tif
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band3.tif
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band7.tif
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band4.tif
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band2.tif
-rw-r--r-- espa/ie   118042071 2015-11-05 04:00 LC81190622014027LGN00_sr_band1.tif
-rw-r--r-- espa/ie    59052384 2015-11-05 04:00 LC81190622014027LGN00_cfmask_conf.tif
```

**Comment by bhbraswell** [comment] 2016-01-07 17:35
Update. I added an asset called "DN" and assigned it the pattern that we are currently using, thinking this should work before adding a new asset.

```
(venv)rbraswell@rio:/titan/data/landsat/stage/rbraswell$ ls -l
total 1006592
-rwxrw-r-- 1 mcorbier  staff 1030521020 Jan  6  2015 LC80130292014244LGN00.tar.gz
drwxrwxr-x 2 rbraswell staff       3896 Jan  7 12:23 save
(venv)rbraswell@rio:/titan/data/landsat/stage/rbraswell$ gips_archive landsat
GIPS Data Archive Utility (v0.8.1)
Data archive error: ''
```

(sigh) See #8.

**Comment by ircwaves** [comment] 2016-01-07 18:05
I like the *DN* asset.  I'm betting that error is coming from somewhere in the `gips.data.landsat` module that isn't getting the asset ID, and is instead just passing `''`.  

If it isn't that, then I would look for functions in `gips.data.core` that are just using `''` instead of retrieving the asset ID from the data class.

**Comment by bhbraswell** [comment] 2016-01-07 18:08
OK. So GIPS apparently assumes that the asset file name begins with a string that is in fact the asset name. In the case of Landsat, it is the empty string. In the case of MODIS, it's MCD43A4, or whatever.

So, if I change the name of the current DN asset from '' to 'L', then it works. Which is kind of good, but not really, because the surface reflectance files also begin with L.

So I'm a little bit smarter but not much farther along. I'm afraid now this will require a change to GIPS core. However I see that the MODIS driver sets self.asset name in it's __init__. I have no idea how this happens by default.

**Comment by ircwaves** [comment] 2016-01-07 18:12
I'll stop by...I haven't seen anything that works off of the asset filename...but I may have missed it.  Is it `gips.core` or `gips.data.core`?

**Comment by bhbraswell** [comment] 2016-01-07 18:20
OK I was totally wrong about the "L" thing. Basically if the asset name is not '', then it doesn't work.

**Comment by bhbraswell** [comment] 2016-01-07 19:24
```
(venv)rbraswell@rio:~/repo/gips$ gips_inventory landsat -t 120061 -d 2015-149 -v4
GIPS Data Inventory (v0.8.1)
Retrieving inventory for site tiles
DN asset
SR asset

Asset Holdings
    DATE        DN        SR     Product  
2015        
    149       100.0%     100.0%     lswi  ndti  ndvi  ref  satvi  tcap


1 files on 1 dates

SENSORS
LC8: Landsat 8
LC8SR: Landsat 8 Surface Reflectance
LE7: Landsat 7
LT5: Landsat 5
```

**Comment by ircwaves** [comment] 2016-01-07 19:29
Verrry nice...and regarding the processing streams that support the SR product

    https://github.com/USGS-EROS/espa-surface-reflectance

**Comment by ircwaves** [comment] 2016-01-08 16:11
Cool.  But I think that we may have to pull this `SR` asset from the
inventory until we can roll out **a** new version of `gips` because #26 is
probably being caused by the old `gips.data.landsat` pattern matching both
tar files:
```
icooke@mekong:~$ pdb `which gips_inventory` landsat -t 120061 -d 2015-149
-v4
> /usr/local/bin/gips_inventory(3)<module>()
-> __requires__ = 'gips==0.8.1'
(Pdb) b
/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/data/core.py:290
Breakpoint 1 at
/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/data/core.py:290
(Pdb) c

** (gips_inventory:1735): WARNING **: Couldn't connect to accessibility
bus: Failed to connect to socket /tmp/dbus-OOldoJBH7E: Connection refused
GIPS Data Inventory (v0.8.1)
Retrieving inventory for site tiles
/titan/data/landsat/tiles/120061/2015149/LC81200612015149LGN00.tar.gz
/titan/data/landsat/tiles/120061/2015149/LC81200612015149-SC20151121043437.tar.gz
>
/usr/local/lib/python2.7/dist-packages/gips-0.8.1-py2.7.egg/gips/data/core.py(290)discover()
-> raise Exception("Duplicate(?) assets found")
(Pdb) l
285             for a in assets:
286                 files = glob.glob(os.path.join(tpath,
cls._assets[a]['pattern']))
287                 # more than 1 asset??
288                 if len(files) > 1:
289                     VerboseOut(files, 2)
290 B->                 raise Exception("Duplicate(?) assets found")
291                 if len(files) == 1:
292                     found.append(cls(files[0]))
293             return found
294
295         @classmethod
(Pdb) files
['/titan/data/landsat/tiles/120061/2015149/LC81200612015149LGN00.tar.gz',
'/titan/data/landsat/tiles/120061/2015149/LC81200612015149-SC20151121043437.tar.gz']
(Pdb)
```

**Comment by bhbraswell** [comment] 2016-01-08 16:20
There's no reason we can't continue to use SR in a virtualenv.

Wait, are you saying we need to delete SR assets from the inventory and therefore not use SR at all?

**Comment by ircwaves** [comment] 2016-01-08 16:29
The reason that you cannot mix `SR` and `DN` *yet* is because old versions of `gips` don't use a specific enough pattern (`L*.tar.gz`) to exclude the `SR` asset, and therefore hitting that tile-date confuses the inventory (*"Two assets?  What do I do with two assets?"*).

**Comment by ircwaves** [comment] 2016-01-08 16:31
In a virtualenv, with a development repo, mixing them would be fine.

**Comment by bhbraswell** [comment] 2016-01-08 16:37
I think this is true only if there is a development archive, is that what you mean?

**Comment by ircwaves** [comment] 2016-01-08 16:44
Yeah, homonyms.  I meant a development (gips) repository, not a development
(git) repository.

**Comment by stephenhagen** [comment] 2016-01-27 15:28
Lindsay is finding landsat SR products in the landsat archive (aka the "DN" archive). I'm not sure if these are left over from some past, now outdated call of `gips_archive` but I want to ask:
what is the current expected result from a call to `gips_archive` on SR products? Will the SR products be archived into the landast_sr archive or the landsat archive?

**Comment by bhbraswell** [comment] 2016-01-27 15:38
The problem is that the most recent version of GIPS includes SR products in the Landsat driver. Those of us who might use GIPS in development mode (this version is not available on rio or nile) have discussed that we need to direct Landsat output to a different archive when using this version. This is obviously an awkward situation and it’s easy to make a mistake. So one shouldn’t run "GIPS_anything landsat”, while in development mode (virtual environment) unless they are pointing to /titan/data/landsat_sr/. Sorry this has caused a problem. I don’t actually know how we should deal with this update.

**Comment by stephenhagen** [comment] 2016-01-27 15:51
Is Lindsay in development mode (virtual environment)? (I don't really know what that means.)

**Comment by lledoux** [comment] 2016-01-27 15:56
I'm not currently in venv mode, and I haven't been doing the gips_projects
in venv mode.  Last week I was trying some things out (just gips_archive
Landsat), which is probably where the SRs got mixed up with the "DNs".
I've put all the SRs that were in the Landsat archive back into my stage,
so there shouldn't be any more problems with that.

**Comment by bhbraswell** [comment] 2016-01-27 15:58
If you check out your own working copy of GIPS, e.g. to make and test some change, you must activate a virtual environment in order to use it. That’s what I’m calling development model. If you are on nile and don’t activate the virtual environment, then you are using the version on nile. Same with rio. If you activate the virtual environment, and are working with the latest version of GIPS, then it knows about SR products. It can make them, and also archive them. However, if you do this, then you must not allow the products to be archived into the common archive. There’s unfortunately no system for us to have a “development” archive. In this case, I created /titan/data/landsat_sr. Anyone using the latest GIPS to do anything with Landsat, should modify their settings.py file so that the archive is “/titan/data/landsat_sr”. Otherwise, SR products could end up in the regular Landsat repository, which causes a problem for the installed GIPS versions. Unfortunately this is not a great system and susceptible to user error.

Rob

**Comment by ircwaves** [comment] 2016-01-27 16:01
The updates of `gips` and `gippy` on our cluster nodes (`nile`, `rio`, and `mekong`) are slated to be done this week.  This will eliminate the need for separate DN and SR archives.

**Comment by ags-tolson** [comment] 2016-10-19 15:54
Closing since there doesn't seem to be any specific work for a GIPS developer here & it's sat idle for ten months; please comment & reopen if you wish.

**Closed by ags-tolson** 2016-10-19 15:54 UTC

**Comment by bhbraswell** [comment] 2016-10-19 16:18
Makes sense @lledoux might be able to report on how things are currently working for surface reflectance product.
