### ISSUE TITLE
MODIS fetching intermittently fails

### ISSUE THREAD

**Issue by ircwaves** [Applied-GeoSolutions/gips#111] opened 2016-10-28 02:00 UTC
Per @ags-tolson's observation, it appears to fetch successfully about half the time via the system tests.

**Comment by bhbraswell** [comment] 2016-10-28 13:06
I can look into this - are there instructions on how to run the tests? sorry I haven't done that yet.

**Comment by ags-tolson** [comment] 2016-10-28 13:22
@bhbraswell Running the system tests may be a little fiddly so here's a workaround.  Here's a command line that had problems yesterday, you can run this a few times and see what you get:

`gips_inventory modis -s /home/tolson/src/gips/gips/test/NHseacoast.shp -d 2012-12-01,2012-12-01 -v 4 --fetch`

It's supposed to fetch the items listed in `gips/test/sys/expected/repo_src_alteration.py` under `t_modis_inv_fetch`.

**Comment by bhbraswell** [comment] 2016-10-28 14:22
```
Exception: Unable to access ftp://n5eil01u.ecs.nsidc.org/SAN/MOST/MOD10A1.005/2012.12.01 --- is it Wednesday?
```

Well, it's not wednesday. Also I can get to this ftp directory in a browser, but only as guest. If I try to authenticate with earthdata crews then it hangs. I assume the driver knows that. I'll check.

**Comment by bhbraswell** [comment] 2016-10-28 14:46
The two assets that failed are MOD10 and MYD10, needed for product fsnow (fractional snow cover).

These are the only two assets fetched through ftp as opposed to http. So it looks like urllib isn't doing it for some reason. 

This is the error from urrlib

```*** IOError: [Errno ftp error] 550 Failed to change directory.```

**Comment by bhbraswell** [comment] 2016-10-28 14:58
Hmm, this works:

```wget ftp://n5eil01u.ecs.nsidc.org/SAN/MOSA/MYD10A1.005/2012.12.01/MYD10A1.A2012336.h15v11.005.2012340032439.hdf```

**Comment by bhbraswell** [comment] 2016-10-28 15:13
python ftplib works so I assume we should update the driver to use it for these assets. does that make sense @ags-tolson ?

```
conn = ftplib.FTP('n5eil01u.ecs.nsidc.org')
conn.login('anonymous','rbraswell@ags.io')
conn.cwd('SAN/MOSA/MYD10A1.005/2012.12.01')
conn.retrlines('LIST')
name = 'MYD10A1.A2012336.h34v10.005.2012340032119.hdf'
conn.retrbinary('RETR '+name, open(name, 'wb').write)
'226 Transfer complete. Checksum matched.'
```

**Comment by ags-tolson** [comment] 2016-10-28 15:25
What is the failure rate over repeated trials?  The original problem is that it _sometimes_ fails.

**Comment by bhbraswell** [comment] 2016-10-28 15:55
I have not seen any successful trials yet for MOD10 or MYD10.

**Comment by ags-tolson** [comment] 2016-10-28 18:52
Update:  I tried the system test for `--fetch` five times today, and it succeeded the first four times, then failed the fifth.  Here's the failure message from GIPS, which corresponds to py.test's finding of missing files after the download:

`Unable to find remote match for (MYD11A1.A2012336.h12v04.\d{3}.\d{13}.hdf) at http://e4ftl01.cr.usgs.gov/MOLA/MYD11A1.005/2012.12.01`

**Comment by bhbraswell** [comment] 2016-10-28 18:59
Ugh

**Comment by bhbraswell** [comment] 2016-11-01 20:02
I can verify that the MOD11 and MYD11 assets which apparently are accessed through ftp, can indeed be accessed by ftp outside of GIPS, using unix ftp and python ftplib; and that they cannot be accessed outside of GIPS using urllib. So I think this means for whatever reason we need to update the driver so that it uses ftplib for ftp-available assets.

**Comment by bhbraswell** [comment] 2016-11-04 19:41
The following fails on my test server at UNH but works on my laptop, oka, probably everywhere else.

```
import ftplib
conn = ftplib.FTP('n5eil01u.ecs.nsidc.org')
conn.login('anonymous','rbraswell@ags.io')
conn.cwd('SAN/MOSA/MYD10A1.005/2012.12.01')
```

**Comment by ircwaves** [comment] 2016-11-04 19:50
unh firewalling ya?  can you do it from ftp/ncftp/wget at UNH?

**Comment by bhbraswell** [comment] 2016-11-04 19:52
It works from a different server in the same room at UNH :-\
Looking into versions of stuff.

**Comment by bhbraswell** [comment] 2016-11-04 19:55
Related to Ian's question - @justinfisk could this be a container thing? Simple iptables fix? Outside of my skill set.

**Comment by justinfisk** [comment] 2016-11-04 20:01
Doh. Looks like I hosed this. Any ftp traffic from within a container is being directed to your ftp site hosted on green. 

I will fix. Sorry about that.

**Comment by bhbraswell** [comment] 2016-11-04 20:03
Ah, I probably asked you to do that.

**Comment by justinfisk** [comment] 2016-11-04 20:09
Try now.

**Comment by bhbraswell** [comment] 2016-11-04 20:35
The FTP problem noted above was a phantom error on the UNH server/ container I am using. So...

I can now report that the test case succeeds for me without complaint.

```
(.venv) braswell@sci3:~/gips/gips$ gips_inventory modis -s /data/test/NHseacoast.shp -d 2012-12-01 -v4 --fetch
GIPS Data Inventory (v0.9.0-dev)
Retrieving inventory for site NHseacoast-0
Retrieved MYD10A1.A2012336.h12v04.005.2012340031954.hdf
Retrieved MOD10A1.A2012336.h12v04.005.2012339213007.hdf
Unable to find remote match for (MOD11A2.A2012336.h12v04.\d{3}.\d{13}.hdf) at http://e4ftl01.cr.usgs.gov/MOLT/MOD11A2.005/2012.12.01
Retrieved MYD11A1.A2012336.h12v04.005.2012341040543.hdf
Retrieved MOD11A1.A2012336.h12v04.005.2012339180517.hdf
Land cover data are only available for Jan. 1
Retrieved MCD43A2.A2012336.h12v04.006.2016112010833.hdf
Retrieved MCD43A4.A2012336.h12v04.006.2016112010833.hdf
MOD10A1.A2012336.h12v04.005.2012339213007.hdf -> /data/gips/modis/tiles/h12v04/2012336/MOD10A1.A2012336.h12v04.005.2012339213007.hdf
MOD11A1.A2012336.h12v04.005.2012339180517.hdf -> /data/gips/modis/tiles/h12v04/2012336/MOD11A1.A2012336.h12v04.005.2012339180517.hdf
MYD10A1.A2012336.h12v04.005.2012340031954.hdf -> /data/gips/modis/tiles/h12v04/2012336/MYD10A1.A2012336.h12v04.005.2012340031954.hdf
MYD11A1.A2012336.h12v04.005.2012341040543.hdf -> /data/gips/modis/tiles/h12v04/2012336/MYD11A1.A2012336.h12v04.005.2012341040543.hdf
MCD43A2.A2012336.h12v04.006.2016112010833.hdf -> /data/gips/modis/tiles/h12v04/2012336/MCD43A2.A2012336.h12v04.006.2016112010833.hdf
MCD43A4.A2012336.h12v04.006.2016112010833.hdf -> /data/gips/modis/tiles/h12v04/2012336/MCD43A4.A2012336.h12v04.006.2016112010833.hdf
6 files (6 links) from /data/gips/modis/stage added to archive in 0:00:00.009769

Asset Coverage for site NHseacoast-0

Tile Coverage
  Tile      % Coverage   % Tile Used
  h12v04      100.0%        0.2%

    DATE     MCD12Q1   MCD43A2   MCD43A4   MOD09Q1   MOD10A1   MOD10A2   MOD11A1   MOD11A2   MYD10A1   MYD10A2   MYD11A1   MYD11A2   Product  
2012        
    336                 100.0%     100.0%               100.0%               100.0%               100.0%               100.0%             


1 files on 1 dates

SENSORS
MCD: Aqua/Terra Combined
MOD: Terra
MOD-MYD: Aqua/Terra together
MYD: Aqua
```

**Comment by justinfisk** [comment] 2016-11-04 20:37
nice of you to call it a "phantom error" instead of "gross incompetence in the floating office"

**Comment by bhbraswell** [comment] 2016-11-05 00:46
As the assignee, I've determined that for me there is no problem. However on AGS there is a problem apparently as determined by @ags-tolson.

**Comment by ags-tolson** [comment] 2016-11-07 17:04
(gah sorry misclick)

**Comment by bhbraswell** [comment] 2016-11-07 17:53
I'm sorry that my "works for me" is not very helpful. I suggest that we unassign this one, or assign it to someone else who might be able to look into what is happening on the AGS side. I think that we suspect AGS firewall (as port mapping caused a similar issue on the UNH side before it was resolved).

**Comment by ircwaves** [comment] 2016-11-07 18:09
WOWOWOWOWOW Two wrong buttons inside of about an hour.  This is possibly a local IT issue.

**Comment by ags-tolson** [comment] 2017-05-05 20:44
So there's no plans to work on this, no definite means to reproduce, and I haven't seen/heard anyone complain in awhile.  I'm going to de-assign myself, mark invalid, and close, and if that's a bad idea, let me know and I'll revert.

**Closed by ags-tolson** 2017-05-05 20:44 UTC
Labels: bug
