### ISSUE TITLE
gips_project Modis only part of area projected (on nile)

### ISSUE THREAD

**Issue by dchowdhury** [Applied-GeoSolutions/gips#28] opened 2016-01-13 17:34 UTC
dchowdhury@nile:/scratch/dchowdhury/VHI$ gips_project Modis -s MS_reproj.shp -d 2009,2016 -p ndvi8 temp8 --res 250 250 --crop

Creates tif's with only part of the data. Shapefile area lies entirely within one single Modis tile h10v05. 

dchowdhury@nile:/scratch/dchowdhury/VHI$ ogrinfo -so -al MS_reproj.shp
INFO: Open of `MS_reproj.shp'
      using driver `ESRI Shapefile' successful.

Layer name: MS_reproj
Geometry: Polygon
Feature Count: 1
Extent: (-8932170.910648, 3916449.445335) - (-8603709.453155, 4440965.500590)
Layer SRS WKT:
PROJCS["NSIDC_EASE_Grid_Global",
    GEOGCS["GCS_Unspecified datum based upon the International 1924 Authalic Sphere",
        DATUM["Not_specified_based_on_International_1924_Authalic_Sphere",
            SPHEROID["International_1924_Authalic_Sphere",6371228,0]],
        PRIMEM["Greenwich",0],
        UNIT["Degree",0.017453292519943295]],
    PROJECTION["Cylindrical_Equal_Area"],
    PARAMETER["standard_parallel_1",30],
    PARAMETER["central_meridian",0],
    PARAMETER["false_easting",0],
    PARAMETER["false_northing",0],
    UNIT["Meter",1]]
NAME: String (32.0)
STATE_NAME: String (25.0)
STATE_FIPS: String (2.0)
CNTY_FIPS: String (3.0)
smb://nile/scratch/dchowdhury/VHI/MS_reproj_250.0x250.0_Modis/0/2009017_MOD_ndvi8.tif
FIPS: String (5.0)
fips_int: Integer (9.0)
true: Integer (1.0)
[2009017_MOD_ndvi8.zip](https://github.com/Applied-GeoSolutions/gips/files/89259/2009017_MOD_ndvi8.zip)

**Comment by ircwaves** [comment] 2016-01-13 18:22
Can you test on `rio`.  This may be another reason to upgrade and get parity of gips version on all servers.

**Comment by dchowdhury** [comment] 2016-01-13 19:01
Yes just checked and the problem persists on rio.

**Comment by ircwaves** [comment] 2016-01-14 14:59
I tested with `MS_reproj_sinu.shp` and the resulting image is correct.  Tested with EPSG:6269 and EPSG:3408, and both showed the same behavior as EPSG:3410.

**Comment by ircwaves** [comment] 2016-01-28 14:13
@dchowdhury  Is this a duplicate of issue #30?

**Closed** 2016-08-22 22:22 UTC
